name: Atualizar README com frase aleatória

on:
  schedule:
    - cron: "0 */6 * * *"  # Atualiza a cada 6 horas
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Rodar script de frases
        run: python script_frase.py

      - name: Commit e push do README atualizado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando frase"
          git push
